version: '{build}'

init:
  - cmd: net start MSSQL$%SQL_Instance%

environment:
  JAVA_HOME: C:\Program Files\Java\jdk9
  mssql_jdbc_test_connection_properties: jdbc:sqlserver://localhost:1433;instanceName=%SQL_Instance%;databaseName=master;username=sa;password=Password12!;

  matrix:
    - SQL_Instance: SQL2008R2SP2
    - SQL_Instance: SQL2016

install:
  - ps: Write-Host 'Installing JCE with powershell'
  - ps: cd AppVeyorJCE
  - ps: choco pack
  - ps: choco install jce -fdv -s . -y -failonstderr
  - ps: cd..
  - ps: mkdir AE_Certificates
  - ps: cd AE_Certificates
  - ps: $cert = New-SelfSignedCertificate -dns "AlwaysEncryptedCert" -CertStoreLocation Cert:CurrentUser\My  
  - ps: $pwd = ConvertTo-SecureString -String "password" -Force -AsPlainText
  - ps: $path = 'cert:\CurrentUser\My\' + $cert.thumbprint
  - ps: $certificate = Export-PfxCertificate -cert $path -FilePath cert.pfx -Password $pwd 
  - ps: Get-ChildItem -path cert:\CurrentUser\My > certificate.txt

cache:
  - C:\Users\appveyor\.m2 -> pom.xml

build_script:
  - keytool -importkeystore -srckeystore cert.pfx -srcstoretype pkcs12 -destkeystore clientcert.jks -deststoretype JKS -srcstorepass password -deststorepass password   
  - keytool -list -v -keystore clientcert.jks -storepass "password" > JavaKeyStore.txt
  - cd..
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Pbuild43
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Pbuild42
  
test_script:
  - mvn test -B -Pbuild43
  - mvn test -B -Pbuild42
